"use client"

import { ArrowRight, TrendingUp, TrendingDown, BarChart, BookOpen, Lightbulb, Layers, Zap } from "lucide-react"

export default function HowItWorks() {
  return (
    <section id="how-it-works" className="py-24 px-6 lg:px-16 bg-white">
      <div className="max-w-7xl mx-auto">
        <div className="flex flex-col md:flex-row animate-fadeInUp pt-6 pr-1 pb-6 pl-1 gap-x-6 gap-y-6 items-start md:items-center mb-12">
          <h2 className="text-[44px] leading-[0.9] sm:text-6xl lg:text-7xl xl:text-5xl text-slate-900 tracking-tighter font-display">
            How Mentron Works
          </h2>
          <span aria-hidden="true" role="separator" className="hidden md:block w-px bg-slate-200 h-10"></span>
          <p className="sm:text-base text-sm text-slate-500 tracking-tight mt-1 max-w-sm">
            Your educational journey, optimized from enrollment to success in 10 simple steps.
          </p>
        </div>

        {/* Row 1 - Steps 1-5 */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6 mb-6">
          {/* Step 1 */}
          <div className="flex flex-col bg-white border-slate-200 border rounded-2xl pt-6 pr-6 pb-6 pl-6 relative shadow-sm hover:shadow-xl transition-all duration-300">
            <span className="absolute -top-3 left-4 inline-flex items-center px-3 py-1 rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-800 shadow-sm">
              STEP 01
            </span>
            <div className="relative h-32 rounded-xl bg-blue-50/50 border border-blue-100 p-3 mb-4">
              <div className="flex gap-2 h-full">
                <div className="bg-white border border-blue-200 rounded-lg p-2 w-1/2 shadow-sm">
                  <div className="w-6 h-6 bg-blue-400 rounded-full mb-1"></div>
                  <div className="h-1 w-12 bg-slate-200 rounded mb-1"></div>
                </div>
                <div className="flex items-center justify-center">
                  <ArrowRight className="text-blue-500 w-4 h-4" />
                </div>
                <div className="flex-1 space-y-1">
                  <div className="h-5 w-full bg-blue-100 rounded"></div>
                  <div className="h-5 w-full bg-slate-50 rounded"></div>
                </div>
              </div>
            </div>
            <h3 className="text-lg text-slate-900 tracking-tight font-display font-bold mb-2">Course Enrollment</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Learner gets added to a course by faculty</p>
          </div>

          {/* Step 2 */}
          <div className="flex flex-col bg-white border-slate-200 border rounded-2xl pt-6 pr-6 pb-6 pl-6 relative shadow-sm hover:shadow-xl transition-all duration-300">
            <span className="absolute -top-3 left-4 inline-flex items-center px-3 py-1 rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-800 shadow-sm">
              STEP 02
            </span>
            <div className="relative h-32 rounded-xl p-3 mb-4" style={{ backgroundColor: "rgba(255, 157, 53, 0.1)", border: "1px solid rgba(255, 157, 53, 0.2)" }}>
              <div className="flex gap-2 h-full items-center">
                <div className="bg-white border border-orange-200 rounded-lg p-2 flex-1">
                  <div className="space-y-1">
                    <div className="h-1 w-full bg-slate-100 rounded"></div>
                    <div className="h-1 w-4/5 bg-slate-100 rounded"></div>
                  </div>
                </div>
                <div className="flex-1 space-y-1">
                  <div className="bg-orange-50 border border-orange-200 rounded p-1">
                    <div className="h-1 w-full bg-orange-300 rounded"></div>
                  </div>
                </div>
              </div>
            </div>
            <h3 className="text-lg text-slate-900 tracking-tight font-display font-bold mb-2">Quiz Generation</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Course enrollment quiz is generated by faculty</p>
          </div>

          {/* Step 3 */}
          <div className="flex flex-col bg-white border-slate-200 border rounded-2xl pt-6 pr-6 pb-6 pl-6 relative shadow-sm hover:shadow-xl transition-all duration-300">
            <span className="absolute -top-3 left-4 inline-flex items-center px-3 py-1 rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-800 shadow-sm">
              STEP 03
            </span>
            <div className="relative h-32 rounded-xl p-2 mb-4" style={{ backgroundColor: "rgba(255, 75, 75, 0.1)", border: "1px solid rgba(255, 75, 75, 0.2)" }}>
              <div className="bg-white border border-red-200 rounded-lg p-2 h-full flex flex-col">
                <div className="space-y-1 flex-1">
                  <div className="flex items-center gap-2 p-1 bg-red-50 border border-red-200 rounded">
                    <div className="w-2 h-2 border-2 border-red-400 rounded-full"></div>
                    <div className="h-1 w-12 bg-red-200 rounded"></div>
                  </div>
                </div>
              </div>
            </div>
            <h3 className="text-lg text-slate-900 tracking-tight font-display font-bold mb-2">Initial Assessment</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Learner takes the course enrollment quiz</p>
          </div>

          {/* Step 4 */}
          <div className="flex flex-col bg-white border-slate-200 border rounded-2xl pt-6 pr-6 pb-6 pl-6 relative shadow-sm hover:shadow-xl transition-all duration-300">
            <span className="absolute -top-3 left-4 inline-flex items-center px-3 py-1 rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-800 shadow-sm">
              STEP 04
            </span>
            <div className="relative h-32 rounded-xl p-3 mb-4" style={{ backgroundColor: "rgba(139, 122, 238, 0.1)", border: "1px solid rgba(139, 122, 238, 0.2)" }}>
              <div className="grid grid-cols-3 gap-1 h-full">
                <div className="bg-white border border-purple-200 rounded-lg p-1 flex flex-col items-center justify-center">
                  <div className="w-4 h-4 bg-purple-400 rounded mb-1"></div>
                  <div className="h-0.5 w-6 bg-purple-200 rounded"></div>
                </div>
                <div className="bg-white border border-purple-200 rounded-lg p-1 flex flex-col items-center justify-center">
                  <div className="w-4 h-4 bg-purple-300 rounded mb-1"></div>
                  <div className="h-0.5 w-5 bg-purple-200 rounded"></div>
                </div>
                <div className="bg-white border border-purple-200 rounded-lg p-1 flex flex-col items-center justify-center">
                  <div className="w-4 h-4 bg-purple-400 rounded mb-1"></div>
                  <div className="h-0.5 w-6 bg-purple-200 rounded"></div>
                </div>
              </div>
            </div>
            <h3 className="text-lg text-slate-900 tracking-tight font-display font-bold mb-2">Knowledge Recording</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Records knowledge of learner even before start of course</p>
          </div>

          {/* Step 5 */}
          <div className="flex flex-col bg-white border-slate-200 border rounded-2xl pt-6 pr-6 pb-6 pl-6 relative shadow-sm hover:shadow-xl transition-all duration-300">
            <span className="absolute -top-3 left-4 inline-flex items-center px-3 py-1 rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-800 shadow-sm">
              STEP 05
            </span>
            <div className="relative h-32 rounded-xl p-3 mb-4" style={{ backgroundColor: "rgba(16, 185, 129, 0.1)", border: "1px solid rgba(16, 185, 129, 0.2)" }}>
              <svg className="w-full h-full" viewBox="0 0 120 100">
                <circle cx="60" cy="50" r="8" fill="#10b981" />
                <line x1="60" y1="50" x2="30" y2="25" stroke="#10b981" strokeWidth="2" />
                <circle cx="30" cy="25" r="6" fill="#34d399" />
                <line x1="60" y1="50" x2="90" y2="25" stroke="#10b981" strokeWidth="2" />
                <circle cx="90" cy="25" r="6" fill="#34d399" />
                <line x1="60" y1="50" x2="60" y2="80" stroke="#10b981" strokeWidth="2" />
                <circle cx="60" cy="80" r="6" fill="#34d399" />
              </svg>
            </div>
            <h3 className="text-lg text-slate-900 tracking-tight font-display font-bold mb-2">Learning Path</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Suggest a learning path based on the learner's strength and weakness</p>
          </div>
        </div>

        {/* Row 2 - Steps 6-10 */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
          {/* Step 6 */}
          <div className="flex flex-col bg-white border-slate-200 border rounded-2xl pt-6 pr-6 pb-6 pl-6 relative shadow-sm hover:shadow-xl transition-all duration-300">
            <span className="absolute -top-3 left-4 inline-flex items-center px-3 py-1 rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-800 shadow-sm">
              STEP 06
            </span>
            <div className="relative h-32 rounded-xl p-3 mb-4" style={{ backgroundColor: "rgba(245, 158, 11, 0.1)", border: "1px solid rgba(245, 158, 11, 0.2)" }}>
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 bg-amber-500 rounded-full"></div>
                  <div className="h-2 flex-1 bg-amber-200 rounded"></div>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 bg-amber-500 rounded-full"></div>
                  <div className="h-2 flex-1 bg-amber-200 rounded"></div>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 bg-amber-400 rounded-full"></div>
                  <div className="h-2 flex-1 bg-amber-100 rounded"></div>
                </div>
              </div>
            </div>
            <h3 className="text-lg text-slate-900 tracking-tight font-display font-bold mb-2">Assignments</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Attends frequent assignments and quizzes generated by faculty</p>
          </div>

          {/* Step 7 */}
          <div className="flex flex-col bg-white border-slate-200 border rounded-2xl pt-6 pr-6 pb-6 pl-6 relative shadow-sm hover:shadow-xl transition-all duration-300">
            <span className="absolute -top-3 left-4 inline-flex items-center px-3 py-1 rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-800 shadow-sm">
              STEP 07
            </span>
            <div className="relative h-32 rounded-xl p-3 mb-4" style={{ backgroundColor: "rgba(59, 130, 246, 0.1)", border: "1px solid rgba(59, 130, 246, 0.2)" }}>
              <div className="flex items-end justify-around h-full gap-1">
                <div className="w-full bg-blue-300 rounded-t" style={{ height: "40%" }}></div>
                <div className="w-full bg-blue-400 rounded-t" style={{ height: "60%" }}></div>
                <div className="w-full bg-blue-500 rounded-t" style={{ height: "80%" }}></div>
                <div className="w-full bg-blue-600 rounded-t" style={{ height: "70%" }}></div>
              </div>
            </div>
            <h3 className="text-lg text-slate-900 tracking-tight font-display font-bold mb-2">Performance Review</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Evaluate performance and suggest areas of improvement</p>
          </div>

          {/* Step 8 */}
          <div className="flex flex-col bg-white border-slate-200 border rounded-2xl pt-6 pr-6 pb-6 pl-6 relative shadow-sm hover:shadow-xl transition-all duration-300">
            <span className="absolute -top-3 left-4 inline-flex items-center px-3 py-1 rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-800 shadow-sm">
              STEP 08
            </span>
            <div className="relative h-32 rounded-xl p-3 mb-4" style={{ backgroundColor: "rgba(168, 85, 247, 0.1)", border: "1px solid rgba(168, 85, 247, 0.2)" }}>
              <div className="grid grid-cols-2 gap-2 h-full">
                <div className="bg-purple-100 rounded-lg p-2 flex items-center justify-center">
                  <TrendingUp className="text-purple-600 w-6 h-6" />
                </div>
                <div className="bg-purple-100 rounded-lg p-2 flex items-center justify-center">
                  <TrendingDown className="text-purple-600 w-6 h-6" />
                </div>
                <div className="col-span-2 bg-purple-200 rounded-lg p-2 flex items-center justify-center">
                  <BarChart className="text-purple-700 w-7 h-7" />
                </div>
              </div>
            </div>
            <h3 className="text-lg text-slate-900 tracking-tight font-display font-bold mb-2">Faculty Reports</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Report strength / weakness from each assessment to course faculty</p>
          </div>

          {/* Step 9 */}
          <div className="flex flex-col bg-white border-slate-200 border rounded-2xl pt-6 pr-6 pb-6 pl-6 relative shadow-sm hover:shadow-xl transition-all duration-300">
            <span className="absolute -top-3 left-4 inline-flex items-center px-3 py-1 rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-800 shadow-sm">
              STEP 09
            </span>
            <div className="relative h-32 rounded-xl p-3 mb-4" style={{ backgroundColor: "rgba(236, 72, 153, 0.1)", border: "1px solid rgba(236, 72, 153, 0.2)" }}>
              <div className="grid grid-cols-2 gap-2 h-full">
                <div className="bg-pink-100 border border-pink-300 rounded-lg flex items-center justify-center">
                  <BookOpen className="text-pink-600 w-5 h-5" />
                </div>
                <div className="bg-pink-100 border border-pink-300 rounded-lg flex items-center justify-center">
                  <Lightbulb className="text-pink-600 w-5 h-5" />
                </div>
                <div className="bg-pink-100 border border-pink-300 rounded-lg flex items-center justify-center">
                  <Layers className="text-pink-600 w-5 h-5" />
                </div>
                <div className="bg-pink-100 border border-pink-300 rounded-lg flex items-center justify-center">
                  <Zap className="text-pink-600 w-5 h-5" />
                </div>
              </div>
            </div>
            <h3 className="text-lg text-slate-900 tracking-tight font-display font-bold mb-2">Learning Aids</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Automatic generation of learning aids based on their weakness</p>
          </div>

          {/* Step 10 */}
          <div className="flex flex-col bg-white border-slate-200 border rounded-2xl pt-6 pr-6 pb-6 pl-6 relative shadow-sm hover:shadow-xl transition-all duration-300">
            <span className="absolute -top-3 left-4 inline-flex items-center px-3 py-1 rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-800 shadow-sm">
              STEP 10
            </span>
            <div className="relative h-32 rounded-xl p-3 mb-4" style={{ backgroundColor: "rgba(20, 184, 166, 0.1)", border: "1px solid rgba(20, 184, 166, 0.2)" }}>
              <div className="flex flex-col h-full gap-2">
                <div className="flex items-center gap-2">
                  <div className="w-6 h-6 bg-teal-200 rounded-full"></div>
                  <div className="flex-1 bg-teal-50 border border-teal-200 rounded-lg p-1.5">
                    <div className="h-1 w-3/4 bg-teal-300 rounded"></div>
                  </div>
                </div>
                <div className="flex items-center gap-2 justify-end">
                  <div className="bg-slate-100 border border-slate-200 rounded-lg p-1.5 w-3/4">
                    <div className="h-1 w-full bg-slate-300 rounded"></div>
                  </div>
                </div>
              </div>
            </div>
            <h3 className="text-lg text-slate-900 tracking-tight font-display font-bold mb-2">24/7 Guidance</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Round-the-clock guidance and feedback for peak performance</p>
          </div>
        </div>
      </div>
    </section>
  )
}
