"use client"
import type React from "react"
import { DualTimeline } from "@/components/ui/dual-timeline"

const organizationSteps = [
  {
    title: "Step 1",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Course Enrollment</h3>
        <p className="text-gray-600 dark:text-gray-400">Learner gets added to a course by faculty</p>
      </div>
    ),
  },
  {
    title: "Step 2",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Quiz Generation</h3>
        <p className="text-gray-600 dark:text-gray-400">Course enrollment quiz is generated by faculty</p>
      </div>
    ),
  },
  {
    title: "Step 3",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Initial Assessment</h3>
        <p className="text-gray-600 dark:text-gray-400">Learner takes the course enrollment quiz</p>
      </div>
    ),
  },
  {
    title: "Step 4",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Knowledge Recording</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Records knowledge of learner even before start of course
        </p>
      </div>
    ),
  },
  {
    title: "Step 5",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Learning Path</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Suggest a learning path based on the learners strength and weakness
        </p>
      </div>
    ),
  },
  {
    title: "Step 6",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Continuous Assessment</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Attends frequent assignments and quizzes generated by faculty with mentron
        </p>
      </div>
    ),
  },
  {
    title: "Step 7",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Performance Evaluation</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Evaluate performance and suggest areas of improvement, update the learning roadmap
        </p>
      </div>
    ),
  },
  {
    title: "Step 8",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Faculty Reporting</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Report strength / weakness from each assessment to course faculty
        </p>
      </div>
    ),
  },
  {
    title: "Step 9",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Learning Aids</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Automatic generation of learning aids for learner based on their weakness
        </p>
      </div>
    ),
  },
]

const individualSteps = [
  {
    title: "Step 1",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Start Session</h3>
        <p className="text-gray-600 dark:text-gray-400">Start a learning session</p>
      </div>
    ),
  },
  {
    title: "Step 2",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Set Goals</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Set a learning goal (own / recommended by mentron based on upcoming assessments)
        </p>
      </div>
    ),
  },
  {
    title: "Step 3",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Todo List</h3>
        <p className="text-gray-600 dark:text-gray-400">Goal will gets added to a learning session todo list</p>
      </div>
    ),
  },
  {
    title: "Step 4",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Learning Roadmap</h3>
        <p className="text-gray-600 dark:text-gray-400">
          A simple overview of what to learn on each goal will be generated (roadmap)
        </p>
      </div>
    ),
  },
  {
    title: "Step 5",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Assessment</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Upon marking a goal in todo as completed learner will be evaluated with an assessment
        </p>
      </div>
    ),
  },
  {
    title: "Step 6",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Instant Feedback</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Given instant feedback to learner about the strengths and weakness from assessment
        </p>
      </div>
    ),
  },
  {
    title: "Step 7",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Auto-Generated Notes</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Automatically generate notes on topics where learner felt weak
        </p>
      </div>
    ),
  },
  {
    title: "Step 8",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Review & Learn</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Learner will learn generated notes again for their clarity
        </p>
      </div>
    ),
  },
  {
    title: "Step 9",
    content: (
      <div>
        <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-gray-200">Final Test</h3>
        <p className="text-gray-600 dark:text-gray-400">
          Ensure learning completion with a final test when all goals are marked completed (will mostly be tested on
          goals where learner poorly performed)
        </p>
      </div>
    ),
  },
]

const LearningJourneySection: React.FC = () => {
  return (
    <section className="w-full bg-white dark:bg-black">
      <DualTimeline
        leftData={organizationSteps}
        rightData={individualSteps}
        leftTitle="Mentron for organizations"
        rightTitle="Mentron for individuals"
        mainTitle="How Mentron Learning journey works?"
      />
    </section>
  )
}

export default LearningJourneySection 